baseURL: https://helenatang.netlify.app/
languageCode: en-us
title: Website for Helena Tang
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Here you can discover my life and hobboes. Start your journey now ~
    title: Welcome to the website for Helena Tang!
  blog: {}
  contact:
    address:
      - city: London
        country: The United Kingdom
        street: Glentworth Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: tyt18810111401@163.com
        title: Email
    enable: yes
    phone:
      - phone: (+0044) 7419 375760
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/Helenatangyt
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100073803976135
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/helena_tangyt/
      - icon: fa-github
        label: GitHub
        url: https://github.com/tythelena
      #- icon: fa-linkedin
       # label: LinkedIn
        #url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: about_me.jpg #about me 
        subtitle: Who am I ? 
        title: About Me
        url: blogs/about_me
      - image: CV.jpg #CV
        subtitle: My CV
        title: My CV
        url: blogs/CV
      - image: hobby.jpg #hobbies
        subtitle: Ballroom dancing
        title: My Hobbies - Ballroom Dancing
        url: blogs/hobby
      - image: exchange.jpg #exchange
        subtitle: My exchange experience in University of British Columbia
        title: Exchange Life
        url: blogs/exchange
      - image: preproject.jpg #preproject
        subtitle: My Preproject
        title: Individual work
        url: blogs/preproject
      - image: groupwork.jpg #group work
        subtitle: Have a look at my group work!
        title: My Group Work
        url: blogs/groupwork
  #two:
  #  buttonText: Get Started
  #  enable: yes
  #  subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
  #    \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
  #    condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
  #    pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
  #    Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
  #    amet pharetra et feugiat tempus."
  # title: Massa libero
  #  url: blogs
